require:
  - rubocop-performance
  - rubocop-rails
  - rubocop-rspec

Style/Documentation:
  Enabled: false

AllCops:
  NewCops: enable
  Exclude:
    - 'bin/**/*'
    - 'db/**/*'
    - 'vendor/**/*'
    - 'config/application.rb'
    - 'config/puma.rb'
    - 'config/environments/*.rb'
    - 'log/*'
    - 'tmp/**/*'
    - 'coverage/**/*'
    - 'public/**/*'
    - 'spec/spec_helper.rb'
    - 'spec/rails_helper.rb'

Metrics/BlockLength:
  IgnoredMethods:
    - context
    - describe

Layout/DotPosition:
  EnforcedStyle: trailing

RSpec/FilePath:
  Enabled: false

RSpec/MultipleExpectations:
  Enabled: false

RSpec/ExampleLength:
  Enabled: false

RSpec/NamedSubject:
  Enabled: false

RSpec/MultipleMemoizedHelpers:
  Enabled: false

RSpec/LetSetup:
  Enabled: false
